from __future__ import annotations

from .api import (
    PluginActivation,
    PluginConfig,
    PluginHostInfo,
    PluginHostInvocation,
    PluginHostLifetime,
    PluginManifest,
    PluginStatus,
    SetupPlugin,
)
from .context import PluginAgentAPI, PluginContext, PluginContextBroker, PluginRegistration, SubmittedTurn, TurnAttachment, UserInput
from .events import EventBus
from .i18n import I18nTextSpec, LocalizedText, PluginI18nRegistry, localize_text
from .manager import PluginManager
from .registry import (
    ActionRegistry,
    ActionSpec,
    CommandRegistry,
    CommandResult,
    CommandSpec,
    OpenPickerAction,
    PickerItem,
    PickerSource,
    RuntimeFunctionSpec,
    RuntimeNamespaceRegistry,
    RuntimeNamespaceSpec,
    SetComposerAction,
    TranscriptAction,
    TranscriptEventSpec,
    UiRegistry,
)
from .resources import ResourceData, ResourceNotFoundError, UnknownResourceProviderError

__all__ = [
    "ActionRegistry",
    "ActionSpec",
    "CommandRegistry",
    "TranscriptAction",
    "SetComposerAction",
    "PickerItem",
    "OpenPickerAction",
    "CommandResult",
    "CommandSpec",
    "EventBus",
    "PickerSource",
    "PluginActivation",
    "PluginAgentAPI",
    "PluginConfig",
    "PluginContext",
    "PluginContextBroker",
    "PluginHostInfo",
    "PluginHostInvocation",
    "PluginHostLifetime",
    "PluginRegistration",
    "PluginManager",
    "PluginManifest",
    "PluginStatus",
    "I18nTextSpec",
    "LocalizedText",
    "PluginI18nRegistry",
    "RuntimeFunctionSpec",
    "RuntimeNamespaceRegistry",
    "RuntimeNamespaceSpec",
    "ResourceData",
    "ResourceNotFoundError",
    "SetupPlugin",
    "SubmittedTurn",
    "TranscriptEventSpec",
    "TurnAttachment",
    "UiRegistry",
    "UnknownResourceProviderError",
    "UserInput",
    "localize_text",
]
